spring:
  profiles:
    active:
    - dev
---
server:
  port: 9001
spring:
  profiles: dev
  application:
    name: supplier
eureka:
  client:
    service-url:
      defaultZone: http://eureka6003.com:6003/eureka
---
server:
  port: 9003
spring:
  profiles: test
  application:
    name: supplier
eureka:
  client:
    service-url:
      defaultZone: http://eureka6003.com:6003/eureka




